In [1]:
import numpy as np

# System matrices
A = np.array([[-2, -1, 2], [-1, -2, 2], [-2, 0, 2]])
B = np.array([[0, 0], [0, 1], [1, 0]])

# Vector f and b
f = np.array([[1], [1]])
b = B @ f

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
v = np.linalg.inv(eigenvectors)

# Projection
p = v[:2, :] @ b

# Display results
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("Inverse of eigenvectors matrix:\n", v)
print("Projection:\n", p)


Eigenvalues:
 [-1.  1. -2.]
Eigenvectors:
 [[-0.80178373  0.40824829 -0.66666667]
 [-0.26726124  0.40824829 -0.66666667]
 [-0.53452248  0.81649658 -0.33333333]]
Inverse of eigenvectors matrix:
 [[-1.87082869e+00  1.87082869e+00 -8.30814836e-16]
 [-1.22474487e+00  4.08248290e-01  1.63299316e+00]
 [-0.00000000e+00 -2.00000000e+00  1.00000000e+00]]
Projection:
 [[1.87082869]
 [2.04124145]]
