In [1]:
import numpy as np
from scipy.signal import StateSpace
from scipy.linalg import eig

# Define the system matrices
A = np.array([[0, 1, 0],
              [0, 0, 4.438],
              [0, -12, -24]])
b1 = np.array([[0],
               [0],
               [20]])
b2 = np.array([[0],
               [-7.396],
               [0]])
B = np.hstack((b1, b2))
C = np.array([[1, 0, 0],
              [0, 1, 0]])
D = np.array([[0], [0]])

# Create a state-space model
DC_motor = StateSpace(A, b1, C, D)  # Note only first input is used

# Compute the eigenvalues and eigenvectors of the matrix A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Compute the eigenvalues and eigenvectors of the transpose of matrix A
eigenvalues_transpose, eigenvectors_transpose = np.linalg.eig(A.T)

# Create diagonal matrices of eigenvalues
e_matrix = np.diag(eigenvalues)
ee_matrix = np.diag(eigenvalues_transpose)

# Print the results
print("v:\n", eigenvectors)
print("ee:\n", e_matrix)
print("v:\n", eigenvectors_transpose)
print("ee:\n", ee_matrix)


v:
 [[ 1.         -0.33290784  0.00938002]
 [ 0.          0.82362581 -0.20191394]
 [ 0.         -0.45914364  0.97935835]]
ee:
 [[  0.           0.           0.        ]
 [  0.          -2.47403548   0.        ]
 [  0.           0.         -21.52596452]]
v:
 [[ 0.          0.          0.90907852]
 [-0.48691774 -0.97940144  0.40967937]
 [-0.87344783 -0.20192283  0.07575654]]
ee:
 [[-21.52596452   0.           0.        ]
 [  0.          -2.47403548   0.        ]
 [  0.           0.           0.        ]]
